services:
  postgres:
    image: postgres:13
    container_name: dbt_postgres
    environment:
      POSTGRES_USER: dbt_container
      POSTGRES_PASSWORD: dbt_container
      POSTGRES_DB: dbt_container
    ports:
      - "5432:5432"
    volumes:
      - ./dbt_lab:/usr/app/dbt_lab
      - dbt_data:/var/lib/postgresql/data
      - ~/.dbt:/root/.dbt
    networks:
      - my-network
    working_dir: /usr/app/dbt_lab

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbt_container -h postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: dbt_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my-network

volumes:
  dbt_data:
  pgadmin_data:

networks:
  my-network:
    driver: bridge
